name: Mini-PaaS CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        app: [app1, app2, app3, app4]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          cd ~/mini-paas
          chmod +x scripts/deploy-k8s.sh
          ./scripts/deploy-k8s.sh ${{ matrix.app }}
